# Generated by Django 3.2.4 on 2021-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
